<?php
namespace Eden\Persistent;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    public function testCookie()
    {
		$class = eden('persistent')->cookie();
		$this->assertInstanceOf('Eden\\Persistent\\Cookie', $class);
    }

    public function testSession()
    {
		$class = eden('persistent')->session();
		$this->assertInstanceOf('Eden\\Persistent\\Session', $class);
    }
}
